# -*- coding: utf-8 -*-
"""vana_test_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTWGc1T2z5cuxPr9U37v0sjdCKPV8w-n
"""

import pandas as pd
import sqlite3

# Define file paths
file_path1 = '/content/sample_data/tbl_src_cnt_master.csv'
file_path2 = '/content/sample_data/tbl_websearch_source_cnt_v1_202510.csv'
db_path = '/content/my_database.db'

# Load CSV files into pandas DataFrames
try:
    df_master = pd.read_csv(file_path1)
    df_websearch = pd.read_csv(file_path2)
except FileNotFoundError as e:
    print(f"Error loading file: {e}")
    # You might want to handle this error more gracefully,
    # perhaps by asking the user for the correct file path.
    exit() # Exit if files are not found

# Create a SQLite database connection
conn = sqlite3.connect(db_path)

# Write DataFrames to SQL tables
try:
    df_master.to_sql('tbl_src_cnt_master', conn, if_exists='replace', index=False)
    df_websearch.to_sql('tbl_websearch_source_cnt_v1_2025', conn, if_exists='replace', index=False)
    print(f"Data from {file_path1} loaded into 'tbl_src_cnt_master' table.")
    print(f"Data from {file_path2} loaded into 'tbl_websearch_source_cnt_v1_2025' table.")
except Exception as e:
    print(f"Error writing to database: {e}")
finally:
    # Close the database connection
    conn.close()



# Commented out IPython magic to ensure Python compatibility.
# %pip install 'vanna[chromadb,openai]'

from vanna.openai import OpenAI_Chat
from vanna.chromadb import ChromaDB_VectorStore

from google.colab import drive
drive.mount('/content/drive')

class MyVanna(ChromaDB_VectorStore, OpenAI_Chat):
    def __init__(self, config=None):
        ChromaDB_VectorStore.__init__(self, config=config)
        OpenAI_Chat.__init__(self, config=config)

vn = MyVanna(config={'api_key': 'OPEN-AI-API-KEY', 'model': 'gpt-4o'})

vn.connect_to_sqlite('/content/my_database.db')



import os
os.environ["ANONYMIZED_TELEMETRY"] = "False"

# Read the content of the file
with open('/content/sample_data/searches_RAG_json_format_3', 'r') as f:
    file_content = f.read()

# Train with the file content
vn.train(documentation=file_content) # Assuming 'documentation' is a valid argument name for passing content

vn.remove_training_data(id = 'e0a0dad9-80ad-516d-9f60-f37faed12a92-sql')
vn.remove_training_data(id = 'f9f5cadd-9948-5c0c-8b40-af0bdaf31b48-doc')

training_data = vn.get_training_data()

training_data

vn.ask(question= 'need deep down analysts of direct category for last 7 days?')

vn.ask(question= 'need overall deep down analysis of last 3 days')

vn.ask(question= 'the direct category searches for the date 5th Oct 2025')

vn.ask(question= 'the sepaid and se nonpaid and direct category searches for the date 5th Oct 2025')

vn.ask(question= 'need the google search count for the date 5th Oct 2025')

vn.ask(question= 'was there any significant drop in company category search counts? ')

vn.ask(question= 'need top category searched between last week?')

vn.ask(question= 'i need category count on for se_paid on 2025-09-29? ')

from vanna.flask import VannaFlaskApp
app = VannaFlaskApp(
    vn,
    allow_llm_to_see_data=True,
    title= 'justdial.com',
    subtitle='kuch-bhi kahi-bhi kabhi-bhi, 0888-888-888',
    logo='https://iili.io/KPA1yRR.png',)
app.run()
